<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<title> Pets </title>';
echo '<link rel="stylesheet" type="text/css" href="css/add&editpet.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Pets</a>';
echo '<a href="#about">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '';
echo '<header>Add Pet</header>';
echo '';
echo '<h1>';
echo '<div class="container">';
echo '<form role="form">';
echo '<!-- Text field -->';
echo '<div class =" form-group ">';
echo '<label for=" inputPetName ">Pet Name</ label >';
echo '<input type ="text" class =" form-control " id=" inputPetName ">';
echo '</div >';
echo '<div class =" form-group ">';
echo '<label for=" inputBreedType ">Breed Type</ label >';
echo '<input type ="text" class =" form-control " id=" inputBreedType ">';
echo '</div >';
echo '<div class =" form-group ">';
echo '<label for=" inputAge ">Age</ label >';
echo '<input type ="text" class =" form-control " id=" inputAge ">';
echo '</div >';
echo '<div class =" form-group ">';
echo '<label for=" inputspecialReq ">Special Requirements</ label >';
echo '<input type ="text" class =" form-control " id=" inputspecialReq ">';
echo '</div >';
echo '</form>';
echo '</div>';
echo '</h1>';
echo '';
echo '<h2>';
echo '<div class="clearfix">';
echo '<button type="next" class="Addpetbtn">Add Pet</button>';
echo '</div>';
echo '</h2>';
echo '</body>';
echo '</html>';
?>