<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<title> History </title>';
echo '<link rel="stylesheet" type="text/css" href="css/history.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Services</a>';
echo '<a href="#about">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '';
echo '<header>History</header>';
echo '';
echo '<div class="container row">';
echo '<h1> Pet 1 </h1>';
echo '<h2> Pet ID: <!-- input php--> </h2>';
echo '<h2> Pet Name: <!-- input php--> </h2>';
echo '<h2> Breed Type: <!-- input php--> </h2>';
echo '<h2> Age: <!-- input php--> </h2>';
echo '<h2> Special Requirements: <!-- input php--> </h2>';
echo '<div class="clearfix">';
echo '<button type="next" class="Leavereviewbtn">Leave Review</button>';
echo '</div>';
echo '</div>';
echo '';
echo '<p> </p>';
echo '';
echo '<div class="container row">';
echo '<h1> Pet 2 </h1>';
echo '<h2> Pet ID: <!-- input php--> </h2>';
echo '<h2> Pet Name: <!-- input php--> </h2>';
echo '<h2> Breed Type: <!-- input php--> </h2>';
echo '<h2> Age: <!-- input php--> </h2>';
echo '<h2> Special Requirements: <!-- input php--> </h2>';
echo '</div>';
echo '</body>';
echo '</html>';
?>