<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Welcome to PAWsome Boarding</title>';
echo '<link rel="stylesheet" type="text/css" href="/css/login-ed.css">';
echo '</head>';
echo '';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Services</a>';
echo '<a href="#about">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '<!-- input display name, gender, email, country, address, birthday -->';
echo '<body>';
echo '<link rel="stylesheet" type="text/css" href="/css/highest-bidder-profile.css">';
echo '<div class="row">';
echo '<center><h1>Highest Bidder's Profile</h1></center>';
echo '<center class="bidder"><div class="profile"><img src="/images/default.jpg"></div>';
echo '<div class="info">';
echo '<p>Display Name:</p>';
echo '<p>Gender:</p>';
echo '<p>Email Address:</p>';
echo '<p>Country:</p>';
echo '<p>Living Address:</p>';
echo '<p>Birthday:</p></div>';
echo '</center>';
echo '<!--split screen into half -->';
echo '<br />';
echo '</div>';
echo '<br>';
echo '<div class="row">';
echo '<center><h1>My Pets</h1></center><br />';
echo '<!-- split -->';
echo '<div class="container">';
echo '<div class="newrow">';
echo '<div class="col-sm-6" style="background-color:#DCC7AA;">';
echo '<div class="combine"><div class="petprofile"><img src="/images/default.jpg" height= "145"></div>';
echo '<div class="petinfo">';
echo '<p>petID:</p>';
echo '<p>Petname:</p>';
echo '<p>Breed Type:</p>';
echo '<p>Age:</p>';
echo '<p>Special Requiremments:</p>';
echo '</div></div>';
echo '</div>';
echo '<div class="col-sm-6" style="background-color:#DCC7AA;">';
echo '<div class="combine"><div class="petprofile"><img src="/images/default.jpg" height= "145"></div>';
echo '<div class="petinfo">';
echo '<p>petID:</p>';
echo '<p>Petname:</p>';
echo '<p>Breed Type:</p>';
echo '<p>Age:</p>';
echo '<p>Special Requiremments:</p>';
echo '</div></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!--may auto-add when got multiple pets -->';
echo '</div>';
echo '</body>';
echo '</html>';
?>