<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<title> Leave A Review </title>';
echo '<link rel="stylesheet" type="text/css" href="css/leavereview.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Pets</a>';
echo '<a href="#about">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '';
echo '<header>Leave A Review</header>';
echo '';
echo '<h1>';
echo '<div class="row">';
echo '<div class="col-25">';
echo '<label for="review">Review</label>';
echo '</div>';
echo '<div class="col-75">';
echo '<textarea id="review" name="review" placeholder="Write something.." style="height:200px"></textarea>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-25">';
echo '<label for="review">Rate</label>';
echo '</div>';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<div class="rate-container">';
echo '<i class="fa fa-star "></i>';
echo '<i class="fa fa-star "></i>';
echo '<i class="fa fa-star "></i>';
echo '<i class="fa fa-star "></i>';
echo '<i class="fa fa-star "></i>';
echo '</div>';
echo '</div>';
echo '</h1>';
echo '';
echo '<h2>';
echo '<div class="clearfix">';
echo '<button type="next" class="Submitbtn">Submit</button>';
echo '</div>';
echo '</h2>';
echo '</body>';
echo '</html>';
?>