<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Highest Bidder</title>';
echo '<link rel="stylesheet" type="text/css" href="/css/login-ed.css">';
echo '</head>';
echo '';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Pets</a>';
echo '<a href="#contact">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '<body>';
echo '<link rel="stylesheet" type="text/css" href="/css/listing.css">';
echo '<div class="container">';
echo '<center><h1>Listing of Caretaker</h1></center>';
echo '<div class="row">';
echo '<div class="col-sm-6" style="background-color:#DCC7AA;">';
echo '<div class="combine"><div class="petprofile"><img src="/images/default.jpg" height= "145"></div>';
echo '<div class="petinfo">';
echo '<p>Name:</p>';
echo '<p>Gender:</p>';
echo '<p>Email Address:</p>';
echo '<p>Country:</p>';
echo '<p>Living Address:</p>';
echo '<p>Birthday:</p>';
echo '<p>Pet Types Accepted:</p>';
echo '<p>Service Type:</p>';
echo '<p>Period:</p>';
echo '';
echo '<p>Reviews</p>';
echo '<div class="review" style="width:600px;height:100px;border:1px solid #000;text-align: center"></div><br>';
echo '<div class="bidinfo" class="review" style="width:200px;height:120px;border:1px solid #000;text-align:left"><div class="form-group"><label for="inputMinBid">Mininum Bid:</label><input type="text" class="form-control" id="inputMinBid"></div>';
echo '<div class="form-group"><label for="inputPetID">PetID:</label><input type="text" class="form-control" id="inputPetID"></div><br><button>Bid</button><p></div><br>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';
?>