<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Login V17</title>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<!--===============================================================================================-->';
echo '<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">';
echo '<!--===============================================================================================-->';
echo '<link rel="stylesheet" type="text/css" href="css/util.css">';
echo '<link rel="stylesheet" type="text/css" href="css/main.css">';
echo '<!--===============================================================================================-->';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="limiter">';
echo '<div class="container-login100">';
echo '<div class="wrap-login100">';
echo '<form class="login100-form validate-form">';
echo '<span class="login100-form-title p-b-34">';
echo 'Account Login';
echo '</span>';
echo '';
echo '<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">';
echo '<input id="first-name" class="input100" type="text" name="username" placeholder="User name">';
echo '<span class="focus-input100"></span>';
echo '</div>';
echo '<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">';
echo '<input class="input100" type="password" name="pass" placeholder="Password">';
echo '<span class="focus-input100"></span>';
echo '</div>';
echo '';
echo '';
echo '<div class="container-login100-form-btn">';
echo '<label class = "checkboxes"><INPUT TYPE="radio" Name="Browser" Value ="Pet Owners"> Pet Owner</INPUT><br>';
echo '<INPUT TYPE="radio" Name= "Browser" Value ="Caretakers"> Caretakers</INPUT></label>';
echo '<button class="login100-form-btn">';
echo 'Sign in';
echo '</button>';
echo '</div>';
echo '';
echo '<div class="w-full text-center p-t-27 p-b-239">';
echo '<span class="txt1">';
echo 'Forgot';
echo '</span>';
echo '';
echo '<a href="#" class="txt2">';
echo 'User name / password?';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="w-full text-center">';
echo '<a href="#" class="txt3">';
echo 'Sign Up';
echo '</a>';
echo '</div>';
echo '</form>';
echo '';
echo '<div class="login100-more" style="background-image: url('images/happy-dog-owner.jpg');"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<div id="dropDownSelect1"></div>';
echo '';
echo '<html>';
?>