<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Welcome to PAWsome Boarding</title>';
echo '<link rel="stylesheet" type="text/css" href="/css/login-ed.css">';
echo '</head>';
echo '';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Service</a>';
echo '<a href="#about">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '';
echo '<div class="split left">';
echo '<center><div class ="txt"><p>List of Owners</p></div></center>';
echo '<div class="centered">';
echo '<div><img src="/images/img_avatar1.jpg" alt="Avatar woman">';
echo '<h2>Jane Flex</h2>';
echo '<p>vbshuvbduvuvebvbeivbfivbciefbvuifevb</p>';
echo '</div>';
echo '';
echo '<div><img src="/images/img_avatar2.jpg" alt="Avatar woman">';
echo '<h2>James hue</h2>';
echo '<p>asdfghjklertyuioxcvbn</p>';
echo '</div>';
echo '';
echo '<div><img src="/images/img_avatar3.jpg" alt="Avatar woman">';
echo '<h2>Jane plina</h2>';
echo '<p>Some njwifbiwbfrif</p>';
echo '</div>';
echo '<button type="button">View More</button>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="split right">';
echo '<center><div class ="txt"><p>Upcoming Events</p></div></center>';
echo '<div class="newcenter">';
echo '<h2>Event 1</h2>';
echo '<p>descriton</p>';
echo '<button type="status">status</button>';
echo '<h2>Event 2</h2>';
echo '<p>description</p>';
echo '<button type="status">status</button>';
echo '<h2>Event 3</h2>';
echo '<p>description</p>';
echo '<button type="status">status</button>';
echo '</div>';
echo '</div>';
echo '</html>';
?>