<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<title> Profile </title>';
echo '<link rel="stylesheet" type="text/css" href="css/profile.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Services</a>';
echo '<a href="#about">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '';
echo '<header>Profile</header>';
echo '';
echo '<h2> First name: <!-- input first name php--> </h2>';
echo '<h2> Last Name: <!-- input last name php--> </h2>';
echo '<h2> Display Name: <!-- input display name php--> </h2>';
echo '<h2> Gender: <!-- input gender php--> </h2>';
echo '<h2> Phone Number: <!-- input phone number php--> </h2>';
echo '<h2> Email: <!-- input email php--> </h2>';
echo '<h2> Country: <!-- input country php--> </h2>';
echo '<h2> Address: <!-- input address php--> </h2>';
echo '<h2> Birthday: <!-- input birthday php--> </h2>';
echo '';
echo '<div class="clearfix">';
echo '<button type="next" class="Updatebtn">Update Profile</button>';
echo '<button type="next" class="Updatebtn">Update Password</button>';
echo '</div>';
echo '</body>';
echo '</html>';
?>