<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<title> Profile </title>';
echo '<link rel="stylesheet" type="text/css" href="css/updatepassword.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="topnav">';
echo '<a class="active" href="#home">Home</a>';
echo '<a href="#news">Profile</a>';
echo '<a href="#contact">Services</a>';
echo '<a href="#about">History</a>';
echo '<form align="right" name="form1" method="post" action="log_out.php">';
echo '<label class="logoutLblPos">';
echo '<input name="submit2" type="submit" id="submit2" value="Log Out">';
echo '</label>';
echo '</form>';
echo '</div>';
echo '';
echo '<header>Update Password</header>';
echo '';
echo '<h1>';
echo '<div class="container">';
echo '<form role="form">';
echo '<!-- Text field -->';
echo '<div class =" form-group ">';
echo '<label for=" inputOPassword ">Old Password</ label >';
echo '<input type ="password" class =" form-control " id=" inputOPassword ">';
echo '</div >';
echo '<div class =" form-group ">';
echo '<label for=" inputNPassword ">New Password</ label >';
echo '<input type ="password" class =" form-control " id=" inputNPassword ">';
echo '</div >';
echo '<div class =" form-group ">';
echo '<label for=" reenterNPassword ">Re-enter New Password</ label >';
echo '<input type ="password" class =" form-control " id=" reenterNPassword ">';
echo '</div >';
echo '</form>';
echo '</div>';
echo '</h1>';
echo '';
echo '<h2>';
echo '<div class="clearfix">';
echo '<button type="next" class="Signupbtn">Update</button>';
echo '</div>';
echo '</h2>';
echo '</body>';
echo '</html>';
echo '';
?>